- hosts: vagrant
            
  tasks:
    - name: loop through a dictionary
      debug: msg="{{ item }}"
      with_dict: "{{ a_dictionary }}"
      tags: dict
    - name: loop through a list
      debug: msg="{{ item }}"
      with_items: "{{ a_list }}"
      tags: list
    
    # - name: Add a domain symlinks /tmp for server_aliases.
    #   debug: msg="name - {{ item.0.name }} and serverAlias - {{ item.1 }}"
    #   with_subelements: 
    #     - apache_vhosts
    #     - server_aliases 
